services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama_new
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    networks:
      - web

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui_new
    volumes:
      - ./backend:/app/backend
    ports:
      - ${OPEN_WEBUI_PORT-5000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY-}
    depends_on:
      - ollama
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}
